### ISSUE TITLE
ISO-TP addressing / Identifier

### ISSUE THREAD

**Issue by HopfArminFronius** [hartkopp/can-isotp-modules#1]
I was testing the isotp kernel module with the shell tools from the can-utils package and compared the behavior with the ISO 15765-2:2016(E) (third edition). 
As far as I understood from the ISO standard, when using the 29 bit CAN Identifier with ISO-TP the identifier should contain a fixed bit-order from 28 to 16 followed by 1 byte for the target address and 1 byte for the source address. From my understanding this CAN Identifier is the same for the FF, FC and CF messages of one specific transfer. 
The isotprecv and isotpsend (from can-utils) are using only the destination address as identifier as far as I saw. The identifier from the FC message also differs to the FF and CF identifier (makes sense in this implementation where the identifier describes the destination only) 

What I would like to know and couldn’t find until now: 

-  Is this behavior known/wanted?
-  What was the use-case for this implementation?

**Comment by hartkopp** [comment]
You mix up different things.
The kernel module implements the transport protocol based on two CAN Identifiers. That is what a  transport protocol has to do for implementing bi-directional segmented transfer of PDUs.

You are talking about how these CAN Identifiers are built in respect to ISO 15765-2:2016.
This is an addressing concept and is separated from the plain transport.

How these CAN Identifiers are calculated is therefore intentionally not the focus of the isotp kernel module. This is something that has to be done by the user application in user space.

E.g. functional addressing in ISO-TP does not deal with segmented transport too. Therefore functional addressing use-cases have to be implemented with a CAN_RAW socket.

The Socket API for CAN_RAW and CAN_ISOTP provide a clean interface to implement CAN functionality to the application programmer. ISO 15765-2:2016 is just putting everything into one spec.

**Comment by HopfArminFronius** [comment]
Thank you very much for the clarification. Now it's clear for me how that module could be used.
