### ISSUE TITLE
can_rx_register prototype in recent kernels added a parameter

### ISSUE THREAD

**Issue by downwith** [hartkopp/can-isotp-modules#2]
I just patched like this:
https://git.alt-teknik.com/nathan/linux-isotp/commit/d3bb87f6cda11d6cad3be80752f402190845c44a

**Comment by hartkopp** [comment]
Hi Nathan,

I really like your clean up of my can-isotp-modules repository!
As I would like to let the current repo AS-IS to have the entire development history ... would it be ok for you that I clone your repo (or at least most of it - and referencing you) to continue the development on that base?

**Comment by downwith** [comment]
Of course.  I use your great work with socketcan and can-utils all the time.  Hobbling together a couple 20-line makefiles was the minimum I could do.
